### ISSUE TITLE
bug error

### ISSUE THREAD

**Issue by samuelacera** [reviewx/Contribute#44]
Fatal error: Uncaught Error: Call to undefined function wc_get_product() in /home/customer/www/academiaspolicia.com/public_html/wp-content/plugins/reviewx/resources/views/admin/pages/manage-all-reviews.php:8 Stack trace: #0 /home/customer/www/academiaspolicia.com/public_html/wp-content/plugins/reviewx/vendor/jouleslabs/warehouse/src/View/View.php(27): include() #1 [internal function]: JoulesLabs\Warehouse\View\View->make('admin/pages/man...', Array, false) #2 /home/customer/www/academiaspolicia.com/public_html/wp-content/plugins/reviewx/vendor/jouleslabs/warehouse/src/Foundation/AppFacade.php(45): call_user_func_array(Array, Array) #3 /home/customer/www/academiaspolicia.com/public_html/wp-content/plugins/reviewx/vendor/jouleslabs/warehouse/src/Supports/common.php(37): JoulesLabs\Warehouse\Foundation\AppFacade::__callStatic('make', Array) #4 /home/customer/www/academiaspolicia.com/public_html/wp-content/plugins/reviewx/app/Modules/Loader.php(166): view('admin.pages.man...', Array) #5 /home/customer/www/academiaspolicia.com in /home/customer/www/academiaspolicia.com/public_html/wp-content/plugins/reviewx/resources/views/admin/pages/manage-all-reviews.php on line 8
Ha habido un error crítico en esta web. Por favor, comprueba la bandeja de entrada del correo electrónico del administrador de tu sitio para obtener instrucciones.

[Aprende más sobre el diagnóstico de WordPress.](https://wordpress.org/support/article/faq-troubleshooting/)

**Comment by arnaimbd** [comment]
Hi @samuelacera, Sorry for the inconvenience. I would appreciate if you could leave a message on our [support channel](https://reviewx.io/support/) so our tech team can get back to you. Thanks.
